# Lab 3
## More EDA: improving expertise in loading, cleaning, and analyzing data

The objective of Lab 3 is for you to become more proficient in obtaining and working with different types of data. A particular emphasis will be on dealing with text data.

This lab assignment will have 3 components. 

## Lab 3.A. Complete tutorials from Harvard's CS109 Lab 1

Go to https://github.com/cs109/2015lab1 and download the following files in your local Lab3 directory:
- https://github.com/cs109/2015lab1/blob/master/Lab1-babypython.ipynb
- https://github.com/cs109/2015lab1/blob/master/Lab1-pythonpandas.ipynb
- https://github.com/cs109/2015lab1/blob/master/all.csv

Study all the code and run every block of code from the *babypython* tutorial. It covers many of the things you already learned in your Labs 1 and 2, so it is a good refresher. However, there are some new things. In particular, you will learn how to load a pure textual file and process it to find counts of all the unique words (also called the tokens) in the text. When going over this tutorial, you can disregard the following blocks of code: 10, 11, 21-23.

Study all the code and run every block of code from the *pythonpandas* tutorial. Again, you will find there many things you already know. However, the novelty here is in processing and analysis of a slightly messy tabular data than was the case with the *Auto MPG data*. When going over this code you can disregard code block 24.

**Deliverable**: submit the two .ipynb files after you have run all the lines of code. We will appreciate if we see that you put some extra effort, such as trying to modify existing code, enter new lines of code, or provide comments in the text. Make sure any modifications are easily visible by us for the grading purposes.

## Lab 3.B. Movie Lens Data

In this part of the lab, you will be working on an exercise that is a slightly modified and shortened version of https://github.com/cs109/2015/blob/master/Lectures/02-DataScrapingQuizzes.ipynb. In particular, you will learn how to load and analyze MoviLens data, which contains ratings of multiple movies by multiple users.

**The MovieLens data**

http://grouplens.org/datasets/movielens/

Take some time to learn about the data, because it will be helpful to do the assignment.

In [1]:
## all imports
from IPython.display import HTML
import numpy as np
import urllib2
import bs4 #this is beautiful soup
import time
import operator
import socket
import cPickle
import re # regular expressions

from pandas import Series
import pandas as pd
from pandas import DataFrame

import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set_context("talk")
sns.set_style("white")

In [2]:
# Read the user data:
#   pass in column names for each CSV
u_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']

users = pd.read_csv(
    'http://files.grouplens.org/datasets/movielens/ml-100k/u.user', 
    sep='|', names=u_cols)

users.head()

   user_id  age sex  occupation zip_code
0        1   24   M  technician    85711
1        2   53   F       other    94043
2        3   23   M      writer    32067
3        4   24   M  technician    43537
4        5   33   F       other    15213

In [3]:
# Read the ratings:
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv(
    'http://files.grouplens.org/datasets/movielens/ml-100k/u.data', 
    sep='\t', names=r_cols)

ratings.head()

   user_id  movie_id  rating  unix_timestamp
0      196       242       3       881250949
1      186       302       3       891717742
2       22       377       1       878887116
3      244        51       2       880606923
4      166       346       1       886397596

In [4]:
# Read the movies data
#  the movies file contains columns indicating the movie's genres
#  let's only load the first five columns of the file with usecols
m_cols = ['movie_id', 'title', 'release_date', 
            'video_release_date', 'imdb_url']

movies = pd.read_csv(
    'http://files.grouplens.org/datasets/movielens/ml-100k/u.item', 
    sep='|', names=m_cols, usecols=range(5))

movies.head()

,movie_id,title,release_date,video_release_date,imdb_url
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995)

Get information about the data:

In [5]:
print movies.dtypes
print
print movies.describe()
# *** Why only those two columns? ***

movie_id                int64
title                  object
release_date           object
video_release_date    float64
imdb_url               object
dtype: object

          movie_id  video_release_date
count  1682.000000                 0.0
mean    841.500000                 NaN
std     485.695893                 NaN
min       1.000000                 NaN
25%     421.250000                 NaN
50%     841.500000                 NaN
75%    1261.750000                 NaN
max    1682.000000                 NaN

Selecting data:

* DataFrame => group of Series with shared index
* single DataFrame column => Series

In [6]:
users.head()
users['occupation'].head()
## *** Where did the nice design go? ***
columns_you_want = ['occupation', 'sex'] 
print users[columns_you_want].head()

print users.head()

print users.iloc[3]

   occupation sex
0  technician   M
1       other   F
2      writer   M
3  technician   M
4       other   F
   user_id  age sex  occupation zip_code
0        1   24   M  technician    85711
1        2   53   F       other    94043
2        3   23   M      writer    32067
3        4   24   M  technician    43537
4        5   33   F       other    15213
user_id                4
age                   24
sex                    M
occupation    technician
zip_code           43537
Name: 3, dtype: object

Filtering data:

Select users older than 25

In [7]:
oldUsers = users[users.age > 25]
oldUsers.head()

   user_id  age sex     occupation zip_code
1        2   53   F          other    94043
4        5   33   F          other    15213
5        6   42   M      executive    98101
6        7   57   M  administrator    91344
7        8   36   M  administrator    05201

**Question 1**: 
* show users aged 40 and male
* show the mean age of female programmers

In [8]:
# users aged 40 AND male
# your code here
print users[(users.age > 40) & (users.sex == 'M')].head()

print '\n'
## users who are female and programmers
# your code here
print users[(users.sex == 'F') & (users.occupation == 'programmer')]

print '\n'
## show statistic summary or compute mean
# your code here
print users.describe()

    user_id  age sex     occupation zip_code
5         6   42   M      executive    98101
6         7   57   M  administrator    91344
9        10   53   M         lawyer    90703
12       13   47   M       educator    29206
13       14   45   M      scientist    55106


     user_id  age sex  occupation zip_code
291      292   35   F  programmer    94703
299      300   26   F  programmer    55106
351      352   37   F  programmer    55105
403      404   29   F  programmer    55108
420      421   38   F  programmer    55105
697      698   28   F  programmer    06906


          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

Find Diligent Users

- split data per user ID
- count ratings
- combine result

In [9]:
print ratings.head()
## split data
grouped_data = ratings.groupby('user_id')
#grouped_data = ratings['movie_id'].groupby(ratings['user_id'])

## count and combine
ratings_per_user = grouped_data.count()

ratings_per_user.head(5)

   user_id  movie_id  rating  unix_timestamp
0      196       242       3       881250949
1      186       302       3       891717742
2       22       377       1       878887116
3      244        51       2       880606923
4      166       346       1       886397596

         movie_id  rating  unix_timestamp
user_id
1             272     272             272
2              62      62              62
3              54      54              54
4              24      24              24
5             175     175             175

**Question 2**:
* get the average rating per movie
* advanced: get the movie titles with the highest average rating

In [25]:
## split data
# your code here
## average and combine
# your code here

grouped_data = ratings.groupby('movie_id')
average_rating = grouped_data['rating'].mean()
print average_rating.head()

print
# get the maximum rating
# your code here
highest_rating = average_rating.max()
print 'higest rating is ', highest_rating

# get movie ids with that rating
# your code here
good_movie_id = average_rating[average_rating == highest_rating].index.tolist()

print
print "Good movie ids:"
print good_movie_id

print "Best movie titles"
print # your code here
print movies[movies['movie_id'].isin(good_movie_id)][['movie_id', 'title']]

print
# get number of ratings per movie
# your code here
num_rating_movie = grouped_data.count()
print "Number of ratings per movie"
print num_rating_movie.head()
#print num_rating_movie.loc[good_movie_id]

movie_id
1    3.878319
2    3.206107
3    3.033333
4    3.550239
5    3.302326
Name: rating, dtype: float64

higest rating is  5.0

Good movie ids:
[814, 1122, 1189, 1201, 1293, 1467, 1500, 1536, 1599, 1653]
Best movie titles

      movie_id                                              title
813        814                      Great Day in Harlem, A (1994)
1121      1122                     They Made Me a Criminal (1939)
1188      1189                                 Prefontaine (1997)
1200      1201         Marlene Dietrich: Shadow and Light (1996)
1292      1293                                    Star Kid (1997)
1466      1467               Saint of Fort Washington, The (1993)
1499      1500                          Santa with Muscles (1996)
1535      1536                               Aiqing wansui (1994)
1598      1599                      Someone Else's America (1995)
1652      1653  Entertaining Angels: The Dorothy Day Story (1996)

Number of ratings per movie
          user_id  rating  unix_timestamp
movie_id
1             452     452             452
2             131     131             131
3              90      90              90
4             209     209             209
5              86      86              86

In [39]:
num_rating = grouped_data.count()
num_rating[average_rating == highest_rating]

          user_id  rating  unix_timestamp
movie_id
814             1       1               1
1122            1       1               1
1189            3       3               3
1201            1       1               1
1293            3       3               3
1467            2       2               2
1500            2       2               2
1536            1       1               1
1599            1       1               1
1653            1       1               1

In [69]:
most_rating = num_rating['rating'].max()
print most_rating
most_rating_id = num_rating[num_rating['rating'] == most_rating].index
print average_rating[most_rating_id]
print
print movies[movies['movie_id'].isin(most_rating_id)]

583
movie_id
50    4.358491
Name: rating, dtype: float64

    movie_id             title release_date  video_release_date  \
49        50  Star Wars (1977)  01-Jan-1977                 NaN

                                             imdb_url
49  http://us.imdb.com/M/title-exact?Star%20Wars%2...

**Question 3**:
* get the average rating per user
* list all occupations and if they are male or female dominant

In [11]:
# get the average rating per user
# your code here
grouped_data = ratings.groupby('user_id')
print grouped_data.count().head()

# list all occupations and if they are male or female dominant
# your code here
print
grouped_data = users.groupby('occupation')['sex']
print grouped_data.apply(lambda x: sum(x == 'M') > sum(x == 'F'))

print
print 'number of male users: '
print sum(users['sex'] == 'M')

print 'number of female users: '
print sum(users['sex'] == 'F')

         movie_id  rating  unix_timestamp
user_id
1             272     272             272
2              62      62              62
3              54      54              54
4              24      24              24
5             175     175             175

occupation
administrator     True
artist            True
doctor            True
educator          True
engineer          True
entertainment     True
executive         True
healthcare       False
homemaker        False
lawyer            True
librarian        False
marketing         True
none              True
other             True
programmer        True
retired           True
salesman          True
scientist         True
student           True
technician        True
writer            True
Name: sex, dtype: bool

number of male users:
670
number of female users:
273

**Question 4**:
- produce a 1-page document that uses a combination of text, tables, and figures that provide some interesting insights about the Movie Lens data. You should feel free to use outside sources to produce the report, as long as you acknowledge your sources.

## Lab 3.C. HTML Data

In this part of the lab, you will be also be working on an exercise that is a slightly modified and shortened version of https://github.com/cs109/2015/blob/master/Lectures/02-DataScrapingQuizzes.ipynb. In particular, you will learn how to load and analyze html data.

HTML:
* HyperText Markup Language
* standard for creating webpages
* HTML tags 
    - have angle brackets
    - typically come in pairs

Below is an example for a minimal webpage defined in HTML tags. The root tag is <html> and then you have the <head> tag. This part of the page typically includes the title of the page and might also have other meta information like the author or keywords that are important for search engines. The <body> tag marks the actual content of the page. You can play around with the <h2> tag trying different header levels. They range from 1 to 6.

In [12]:
htmlString = """<!DOCTYPE html>
<html>
  <head>
    <title>This is a title</title>
  </head>
  <body>
    <h2> Test </h2>
    <p>Hello world!</p>
  </body>
</html>"""

htmlOutput = HTML(htmlString)
htmlOutput

Useful Tags:

* heading
`<h1></h1> ... <h6></h6>`

* paragraph
`<p></p>` 

* line break
`<br>` 

* link with attribute

`<a href="http://www.example.com/">An example link</a>`

### Scraping with Python:

Example of a simple webpage: http://www.crummy.com/software/BeautifulSoup

Good news: 
    - some browsers help
    - look for: inspect element
    - need only basic html
    - try 'Ctrl-Shift I' in Chrome
    - try 'Command-Option I' in Safari
   
Different useful libraries:
    - urllib
    - beautifulsoup
    - pattern
    - soupy
    - LXML
    - ...
 
The following cell just defines a url as a string and then reads the data from that url using the `urllib` library. If you uncomment the print command you see that we got the whole HTML content of the page into the string variable source.

In [13]:
url = 'http://www.crummy.com/software/BeautifulSoup'
source = urllib2.urlopen(url).read()
print source

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"
"http://www.w3.org/TR/REC-html40/transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Beautiful Soup: We called him Tortoise because he taught us.</title>
<link rev="made" href="mailto:leonardr@segfault.org">
<link rel="stylesheet" type="text/css" href="/nb/themes/Default/nb.css">
<meta name="Description" content="Beautiful Soup: a library designed for screen-scraping HTML and XML.">
<meta name="generator" content="Markov Approximation 1.4 (module: leonardr)">
<meta name="author" content="Leonard Richardson">
</head>
<body bgcolor="white" text="black" link="blue" vlink="660066" alink="red">
<img align="right" src="10.1.jpg" width="250"><br />

<p>You didn't write that awful page. You're just trying to get some
data out of it. Beautiful Soup is here to help. Since 2004, it's been
saving programmers hours or days of work on quick-turnaround
screen scraping projects.</p>

<div align="center">

<a href="bs4/download/"><h1>Beautiful Soup</h1></a>

<p>"A tremendous boon." -- Python411 Podcast</p>

<p>[ <a href="#Download">Download</a> | <a
href="bs4/doc/">Documentation</a> | <a href="#HallOfFame">Hall of Fame</a> | <a href="https://code.launchpad.net/beautifulsoup">Source</a> | <a href="https://groups.google.com/forum/?fromgroups#!forum/beautifulsoup">Discussion group</a>  | <a href="zine/">Zine</a> ]</p>

<small>If Beautiful Soup has saved you a lot of time and money, one way to pay me back is to read <a href="zine/"><i>Tool Safety</i></a>, a short zine I wrote about what I learned about software development from working on Beautiful Soup. Thanks!</small> </div>

<p><i>If you have questions, send them to <a
href="https://groups.google.com/forum/?fromgroups#!forum/beautifulsoup">the discussion
group</a>. If you find a bug, <a href="https://bugs.launchpad.net/beautifulsoup/">file it</a>.</i></p>

<p>Beautiful Soup is a Python library designed for quick turnaround
projects like screen-scraping. Three features make it powerful:

<ol>

<li>Beautiful Soup provides a few simple methods and Pythonic idioms
for navigating, searching, and modifying a parse tree: a toolkit for
dissecting a document and extracting what you need. It doesn't take
much code to write an application

<li>Beautiful Soup automatically converts incoming documents to
Unicode and outgoing documents to UTF-8. You don't have to think
about encodings, unless the document doesn't specify an encoding and
Beautiful Soup can't detect one. Then you just have to specify the
original encoding.

<li>Beautiful Soup sits on top of popular Python parsers like <a
href="http://lxml.de/">lxml</a> and <a
href="http://code.google.com/p/html5lib/">html5lib</a>, allowing you
to try out different parsing strategies or trade speed for
flexibility.

</ol>

<p>Beautiful Soup parses anything you give it, and does the tree
traversal stuff for you. You can tell it "Find all the links", or
"Find all the links of class <tt>externalLink</tt>", or "Find all the
links whose urls match "foo.com", or "Find the table heading that's
got bold text, then give me that text."

<p>Valuable data that was once locked up in poorly-designed websites
is now within your reach. Projects that would have taken hours take
only minutes with Beautiful Soup.

<p>Interested? <a href="bs4/doc/">Read more.</a>

<a name="Download"><h2>Download Beautiful Soup</h2></a>

<p>The current release is <a href="bs4/download/">Beautiful Soup
4.6.0</a> (May 7, 2017). You can install Beautiful Soup 4 with
<code>pip install beautifulsoup4</code>.

<p>In Debian and Ubuntu, Beautiful Soup is available as the
<code>python-bs4</code> package (for Python 2) or the
<code>python3-bs4</code> package (for Python 3). In Fedora it's
available as the <code>python-beautifulsoup4</code> package.

<p>Beautiful Soup is licensed under the MIT license, so you can also
download the tarball, drop the <code>bs4/</code> directory into almost
any Python application (or into your library path) and start using it
immediately. (If you want to do this under Python 3, you will need to
manually convert the code using <code>2to3</code>.)

<p>Beautiful Soup 4 works on both Python 2 (2.7+) and Python 3.

<h3>Beautiful Soup 3</h3>

<p>Beautiful Soup 3 was the official release line of Beautiful Soup
from May 2006 to March 2012. It is considered stable, and only
critical security bugs will be fixed. <a
href="http://www.crummy.com/software/BeautifulSoup/bs3/documentation.html">Here's
the Beautiful Soup 3 documentation.</a>

<p>Beautiful Soup 3 works only under Python 2.x. It is licensed under
the same license as Python itself.

<p>The current release of Beautiful Soup 3 is <a
href="download/3.x/BeautifulSoup-3.2.1.tar.gz">3.2.1</a> (February 16,
2012). You can install Beautiful Soup 3 with <code>pip install
BeautifulSoup</code>. It's also available as
<code>python-beautifulsoup</code> in Debian and Ubuntu, and as
<code>python-BeautifulSoup</code> in Fedora.

<p>You can also download the tarball and use
<code>BeautifulSoup.py</code> in your project directly.


<a name="HallOfFame"><h2>Hall of Fame</h2></a>

<p>Over the years, Beautiful Soup has been used in hundreds of
different projects. There's no way I can list them all, but I want to
highlight a few high-profile projects. Beautiful Soup isn't what makes
these projects interesting, but it did make their completion easier:

<ul>

<li><a
 href="http://www.nytimes.com/2007/10/25/arts/design/25vide.html">"Movable
 Type"</a>, a work of digital art on display in the lobby of the New
 York Times building, uses Beautiful Soup to scrape news feeds.

<li>Reddit uses Beautiful Soup to <a
href="https://github.com/reddit/reddit/blob/85f9cff3e2ab9bb8f19b96acd8da4ebacc079f04/r2/r2/lib/media.py">parse
a page that's been linked to and find a representative image</a>.

<li>Alexander Harrowell uses Beautiful Soup to <a
 href="http://www.harrowell.org.uk/viktormap.html">track the business
 activities</a> of an arms merchant.

<li>The developers of Python itself used Beautiful Soup to <a
href="http://svn.python.org/view/tracker/importer/">migrate the Python
bug tracker from Sourceforge to Roundup</a>.

<li>The <a href="http://www2.ljworld.com/">Lawrence Journal-World</a>
uses Beautiful Soup to <A
href="http://www.b-list.org/weblog/2010/nov/02/news-done-broke/">gather
statewide election results</a>.

<li>The <a href="http://esrl.noaa.gov/gsd/fab/">NOAA's Forecast
Applications Branch</a> uses Beautiful Soup in <a
href="http://laps.noaa.gov/topograbber/">TopoGrabber</a>, a script for
downloading "high resolution USGS datasets."

</ul>

<p>If you've used Beautiful Soup in a project you'd like me to know
about, please do send email to me or <a
href="http://groups.google.com/group/beautifulsoup/">the discussion
group</a>.

<h2>Development</h2>

<p>Development happens at <a
href="https://launchpad.net/beautifulsoup">Launchpad</a>. You can <a
href="https://code.launchpad.net/beautifulsoup/">get the source
code</a> or <a href="https://bugs.launchpad.net/beautifulsoup/">file
bugs</a>.<hr><table><tr><td valign="top">
<p>This document (<a href="/source/software/BeautifulSoup/index.bhtml">source</a>) is part of Crummy, the webspace of <a href="/self/">Leonard Richardson</a> (<a href="/self/contact.html">contact information</a>). It was last modified on Friday, August 11 2017, 14:19:20 Nowhere Standard Time and last built on Wednesday, February 07 2018, 17:00:01 Nowhere Standard Time.</p><p><table class="licenseText"><tr><td><a href="http://creativecommons.org/licenses/by-sa/2.0/"><img border="0" src="/nb//resources/img/somerights20.jpg"></a></td><td valign="top">Crummy is &copy; 1996-2018 Leonard Richardson. Unless otherwise noted, all text licensed under a <a href="http://creativecommons.org/licenses/by-sa/2.0/">Creative Commons License</a>.</td></tr></table></span><!--<rdf:RDF xmlns="http://web.resource.org/cc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><Work rdf:about="http://www.crummy.com/"><dc:title>Crummy: The Site</dc:title><dc:rights><Agent><dc:title>Crummy: the Site</dc:title></Agent></dc:rights><dc:format>text/html</dc:format><license rdf:resource=http://creativecommons.org/licenses/by-sa/2.0//></Work><License rdf:about="http://creativecommons.org/licenses/by-sa/2.0/"></License></rdf:RDF>--></p></td><td valign=top><p><b>Document tree:</b>
<dl><dd><a href="http://www.crummy.com/">http://www.crummy.com/</a><dl><dd><a href="http://www.crummy.com/software/">software/</a><dl><dd><a href="http://www.crummy.com/software/BeautifulSoup/">BeautifulSoup/</a></dl>
</dl>
</dl>


Site Search:

<form method="get" action="/search/">
        <input type="text" name="q" maxlength="255" value=""></input>
        </form>
        </td>

</tr>

</table>
</body>
</html>

**Question 5**:

* Is the word 'Alice' mentioned on the beautiful soup homepage?
* How often does the word 'Soup' occur on the site?
    - hint: use `.count()`
* At what index occurs the substring 'alien video games' ?
    - hint: use `.find()`

In [14]:
## is 'Alice' in source?
print 'Alice' in source

## count occurences of 'Soup'
print source.count('Soup')

## find index of 'alien video games'
print source.find('alien video games')

False
43
-1

**Beautiful Soup**

* designed to make your life easier
* many good functions for parsing html code

Some examples:

In [15]:
## get bs4 object
soup = bs4.BeautifulSoup(source)
 
## compare the two print statements
# print soup
# print soup.prettify()

## show how to find all a tags
soup.findAll('a')

## ***Why does this not work? ***
# soup.findAll('Soup')

C:\Users\Hoang\Anaconda2\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 174 of the file C:\Users\Hoang\Anaconda2\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))

[<a href="bs4/download/"><h1>Beautiful Soup</h1></a>,
 <a href="#Download">Download</a>,
 <a href="bs4/doc/">Documentation</a>,
 <a href="#HallOfFame">Hall of Fame</a>,
 <a href="https://code.launchpad.net/beautifulsoup">Source</a>,
 <a href="https://groups.google.com/forum/?fromgroups#!forum/beautifulsoup">Discussion group</a>,
 <a href="zine/">Zine</a>,
 <a href="zine/"><i>Tool Safety</i></a>,
 <a href="https://groups.google.com/forum/?fromgroups#!forum/beautifulsoup">the discussion\ngroup</a>,
 <a href="https://bugs.launchpad.net/beautifulsoup/">file it</a>,
 <a href="http://lxml.de/">lxml</a>,
 <a href="http://code.google.com/p/html5lib/">html5lib</a>,
 <a href="bs4/doc/">Read more.</a>,
 <a name="Download"><h2>Download Beautiful Soup</h2></a>,
 <a href="bs4/download/">Beautiful Soup\n4.6.0</a>,
 <a href="http://www.crummy.com/software/BeautifulSoup/bs3/documentation.html">Here's\nthe Beautiful Soup 3 documentation.</a>,
 <a href="download/3.x/BeautifulSoup-3.2.1.tar.gz">3.2.1</a>,
 <a name="HallOfFame"><h2>Hall of Fame</h2></a>,
 <a href="http://www.nytimes.com/2007/10/25/arts/design/25vide.html">"Movable\n Type"</a>,
 <a href="https://github.com/reddit/reddit/blob/85f9cff3e2ab9bb8f19b96acd8da4ebacc079f04/r2/r2/lib/media.py">parse\na page that's been linked to and find a representative image</a>,
 <a href="http://www.harrowell.org.uk/viktormap.html">track the business\n activities</a>,
 <a href="http://svn.python.org/view/tracker/importer/">migrate the Python\nbug tracker from Sourceforge to Roundup</a>,
 <a href="http://www2.ljworld.com/">Lawrence Journal-World</a>,
 <a href="http://www.b-list.org/weblog/2010/nov/02/news-done-broke/">gather\nstatewide election results</a>,
 <a href="http://esrl.noaa.gov/gsd/fab/">NOAA's Forecast\nApplications Branch</a>,
 <a href="http://laps.noaa.gov/topograbber/">TopoGrabber</a>,
 <a href="http://groups.google.com/group/beautifulsoup/">the discussion\ngroup</a>,
 <a href="https://launchpad.net/beautifulsoup">Launchpad</a>,
 <a href="https://code.launchpad.net/beautifulsoup/">get the source\ncode</a>,
 <a href="https://bugs.launchpad.net/beautifulsoup/">file\nbugs</a>,
 <a href="/source/software/BeautifulSoup/index.bhtml">source</a>,
 <a href="/self/">Leonard Richardson</a>,
 <a href="/self/contact.html">contact information</a>,
 <a href="http://creativecommons.org/licenses/by-sa/2.0/"><img border="0" src="/nb//resources/img/somerights20.jpg"/></a>,
 <a href="http://creativecommons.org/licenses/by-sa/2.0/">Creative Commons License</a>,
 <a href="http://www.crummy.com/">http://www.crummy.com/</a>,
 <a href="http://www.crummy.com/software/">software/</a>,
 <a href="http://www.crummy.com/software/BeautifulSoup/">BeautifulSoup/</a>]

More examples:

In [16]:
## get attribute value from an element:
## find tag: this only returns the first occurrence, not all tags in the string
first_tag = soup.find('a')

## get attribute `href`
first_tag.get('href')

## get all links in the page
link_list = [l.get('href') for l in soup.findAll('a')]
link_list

['bs4/download/',
 '#Download',
 'bs4/doc/',
 '#HallOfFame',
 'https://code.launchpad.net/beautifulsoup',
 'https://groups.google.com/forum/?fromgroups#!forum/beautifulsoup',
 'zine/',
 'zine/',
 'https://groups.google.com/forum/?fromgroups#!forum/beautifulsoup',
 'https://bugs.launchpad.net/beautifulsoup/',
 'http://lxml.de/',
 'http://code.google.com/p/html5lib/',
 'bs4/doc/',
 None,
 'bs4/download/',
 'http://www.crummy.com/software/BeautifulSoup/bs3/documentation.html',
 'download/3.x/BeautifulSoup-3.2.1.tar.gz',
 None,
 'http://www.nytimes.com/2007/10/25/arts/design/25vide.html',
 'https://github.com/reddit/reddit/blob/85f9cff3e2ab9bb8f19b96acd8da4ebacc079f04/r2/r2/lib/media.py',
 'http://www.harrowell.org.uk/viktormap.html',
 'http://svn.python.org/view/tracker/importer/',
 'http://www2.ljworld.com/',
 'http://www.b-list.org/weblog/2010/nov/02/news-done-broke/',
 'http://esrl.noaa.gov/gsd/fab/',
 'http://laps.noaa.gov/topograbber/',
 'http://groups.google.com/group/beautifulsoup/',
 'https://launchpad.net/beautifulsoup',
 'https://code.launchpad.net/beautifulsoup/',
 'https://bugs.launchpad.net/beautifulsoup/',
 '/source/software/BeautifulSoup/index.bhtml',
 '/self/',
 '/self/contact.html',
 'http://creativecommons.org/licenses/by-sa/2.0/',
 'http://creativecommons.org/licenses/by-sa/2.0/',
 'http://www.crummy.com/',
 'http://www.crummy.com/software/',
 'http://www.crummy.com/software/BeautifulSoup/']

In [17]:
## filter all external links
# create an empty list to collect the valid links
external_links = []

# write a loop to filter the links
# if it starts with 'http' we are happy
for l in link_list:
    if l[:4] == 'http':
        external_links.append(l)

# this throws an error! It says something about 'NoneType'

TypeError: 'NoneType' object has no attribute '__getitem__'

In [ ]:
# lets investigate. Have a close look at the link_list:
link_list

# Seems that there are None elements!
# Let's verify
#print sum([l is None for l in link_list])

# So there are two elements in the list that are None!

In [ ]:
# Let's filter those objects out in the for loop
external_links = []

# write a loop to filter the links
# if it is not None and starts with 'http' we are happy
for l in link_list:
    if l is not None and l[:4] == 'http':
        external_links.append(l)
        
external_links

*Note*: The above `if` condition works because of lazy evaluation in Python. The `and` statement becomes `False` if the first part is `False`, so there is no need to ever evaluate the second part. Thus a `None` entry in the list gets never asked about its first four characters.

In [ ]:
# and we can put this in a list comprehension as well, it almost reads like 
# a sentence.

[l for l in link_list if l is not None and l.startswith('http')]

Parsing the Tree:

In [ ]:
# redifining `s` without any line breaks
s = """<!DOCTYPE html><html><head><title>This is a title</title></head><body><h3> Test </h3><p>Hello world!</p></body></html>"""
## get bs4 object
tree = bs4.BeautifulSoup(s)

## get html root node
root_node = tree.html

## get head from root using contents
head = root_node.contents[0]

## get body from root
body = root_node.contents[1]

## could directly access body
print tree.body
print root_node
print head
print body

**Question 6**:

* Find the `h3` tag by parsing the tree starting at `body`
* Create a list of all __Hall of Fame__ entries listed on the Beautiful Soup webpage
    - hint: it is the only unordered list in the page (tag `ul`)

In [ ]:
## get h3 tag from body
print tree.body.contents[0]

print 
## use ul as entry point
entry_point = soup.find('ul')
print entry_point.contents
print
hall_of_fame = entry_point.contents[1:]
print hall_of_fame
## get hall of fame list from entry point
## skip the first entry 

## reformat into a list containing strings
## it is ok to have a list of lists
tmp = [li.contents for li in hall_of_fame]
tmp

`tmp` now is actually a list of lists containing the hall of fame entries. 
Here is some advanced Python on how to print really just one entry per list item.

The cool things about this are: 
* The use of `""` to just access the `join` function of strings.
* The `join` function itself
* that you can actually have two nested for loops in a list comprehension

In [ ]:
test =  ["".join(str(a) for a in sublist) for sublist in tmp]
print '\n'.join(test)

**Question 7**:
- Explain in detail what is Python doing in the previous line

**Question 8**:
- Plot a histogram of the count of the 20 most common words in the html file
- Plot a histogram of the count of the 20 most common words in the visible part (what is displayed in the browser) of the html file

**Deliverable**: For Lab 3.B and 3.C submit a modified version fo this .ipynb file that contains all the answers to the quesitons

###Question 7

For each sublist inside tmp, we turn each element in the sublist into string type and use ''.join to connect them into 1 string. test is now a list of strings with length 5. In order to have a nice print, we use .join again to connect elements in test: each element in test is connected by a white line.

In [ ]:
#Question 8
#Plot a Histogram of the count of the 20 most common words in the html file
newSource = re.findall(r'\w+', source)
from collections import Counter
word_counts = Counter(newSource).most_common(20)
print(word_counts)
word, frequency = [list(t) for t in zip(*word_counts)]
indices = np.arange(len(word))
plt.figure(figsize = (10,5))
plt.bar(indices, frequency, color='b')
plt.xticks(indices, word, rotation='vertical')
plt.tight_layout()
plt.show()

In [ ]:
#Question 8
#Plot Histogram of the Count of the 20 most common words in the visible part of the html file
# from collections import Counter
# from string import punctuation
# text = (''.join(s.findAll(text = True)) for s in soup.findAll('p'))
# c = Counter((x.rstrip(punctuation) for y in text for x in y.split()))
# word_counts2 = c.most_common(20)
# print word_counts2
# word, frequency = [list(t) for t in zip(*word_counts2)]
# indices = np.arange(len(word))
# plt.figure(figsize = (10,5))
# plt.bar(indices, frequency, color='b')
# plt.xticks(indices, word, rotation='vertical')
# plt.tight_layout()
# plt.show()

In [ ]:
#Question 8
#Plot Histogram of the Count of the 20 most common words in the visible part of the html file
text = [' '.join(s.findAll(text = True)) for s in soup.findAll('p')]
listsText = [re.findall(r'\w+', s) for s in text] 
newText = [l for sublist in listsText for l in sublist]
word_counts3 = Counter(newText).most_common(20)
print word_counts3
word, frequency = [list(t) for t in zip(*word_counts3)]
indices = np.arange(len(word))
plt.figure(figsize = (10,5))
plt.bar(indices, frequency, color='b')
plt.xticks(indices, word, rotation='vertical')
plt.tight_layout()
plt.show()