In [1]:
import pandas as pd

In [2]:
business = pd.read_csv("business_cleaned.csv")

In [3]:
business.head()

,postal_code,hours.Thursday,hours.Friday,latitude,business_id,categories,name,is_open,neighborhood,review_count,...,address,hours.Sunday,hours.Wednesday,hours.Monday,city,hours.Tuesday,stars,longitude,hours.Saturday,attributes
0,L3P 1X3,NaN,NaN,43.875177,xcgFnd-MwkZeO5G2HQ0gAQ,"['Bakeries', 'Bagels', 'Food']",T & T Bakery and Cafe,1,Markham Village,38,...,35 Main Street N,NaN,NaN,NaN,Markham,NaN,4.0,-79.260153,NaN,"['BusinessParking_lot', 'BusinessParking_stree..."
1,M4P 2H6,9:00-22:00,9:00-22:00,43.711399,l09JfMeQ6ynYs5MCJtrcmQ,"['Italian', 'French', 'Restaurants']",Alize Catering,0,Yonge and Eglinton,12,...,2459 Yonge St,9:00-22:00,9:00-22:00,9:00-22:00,Toronto,9:00-22:00,3.0,-79.399339,9:00-22:00,"['RestaurantsTableService', 'BusinessAcceptsCr..."
2,L4C 9V4,11:30-22:00,11:30-23:00,43.867565,Gu-xs3NIQTj3Mj2xYoN2aw,"['French', 'Food', 'Bakeries', 'Restaurants']",Maxim Bakery & Restaurant,1,NaN,34,...,"9665 Bayview Avenue, Unit 1-4",11:00-22:00,11:30-22:00,11:30-22:00,Richmond Hill,11:30-22:00,3.5,-79.412662,11:00-23:00,"['RestaurantsTableService', 'RestaurantsGoodFo..."
3,M6K 3S3,5:30-22:00,5:30-23:00,43.639863,lHYiCS-y8AFjUitv6MGpxg,"['Food', 'Coffee & Tea']",Starbucks,1,Liberty Village,21,...,85 Hanna Avenue,7:00-22:00,5:30-22:00,5:30-22:00,Toronto,5:30-22:00,4.0,-79.419533,6:00-23:00,"['WheelchairAccessible', 'BusinessAcceptsCredi..."
4,M4M 3A6,11:30-2:00,11:30-2:00,43.669256,1K4qrnfyzKzGgJPBEcJaNQ,"['Tiki Bars', 'Nightlife', 'Mexican', 'Restaur...",Chula Taberna Mexicana,1,Leslieville,39,...,1058 Gerrard Street E,10:30-2:00,11:30-2:00,11:30-2:00,Toronto,11:30-2:00,3.5,-79.335902,10:30-2:00,"['RestaurantsTableService', 'RestaurantsGoodFo..."

In [4]:
user = pd.read_csv("user_cleaned.csv")

In [5]:
user.head()

,yelping_since,useful,compliment_photos,compliment_list,compliment_funny,compliment_plain,elite,fans,compliment_note,funny,...,average_stars,user_id,compliment_more,friends,compliment_hot,cool,name,compliment_profile,compliment_cool,review_count
0,2015-05-18,5,0,0,0,1,[],0,1,2,...,2.00,1iIebpwPVifig9Xi0EI8Dg,0,[],0,0,Ella,0,0,4
1,2013-10-04,0,0,0,0,0,[],0,0,0,...,4.36,soTbfMymlIGp9nTLiYKtxQ,0,[],0,0,Heaton,0,0,3
2,2016-10-21,1,0,0,0,0,[],0,0,0,...,4.50,WnI11IQwx-pcjTOEejGJsg,0,[],0,0,Alexa,0,0,3
3,2014-03-17,51,4,0,13,16,"[2016, 2017, 2014, 2015]",13,5,12,...,3.71,i5jSTSpXJtvM-ExWRttglw,1,"[u'aLvxbF2DueKFOqul9eVWCw', u'JesJ-LaNfr3pKhL7...",10,33,Evelina,0,13,55
4,2017-01-30,4,0,0,0,0,[],0,0,0,...,3.92,2f_pVxImXu2Y6SclpAEXZg,0,[],0,0,Alex,0,0,11

In [7]:
review = pd.read_csv("review_cleaned.csv")

In [8]:
review.head()

,funny,user_id,review_id,text,business_id,stars,date,useful,cool
0,0,u0LXt3Uea_GidxRW1xcsfg,ymAUG8DZfQcFTBSOiaNN4w,Who would have guess that you would be able to...,9_CGhHMz8698M9-PkVf0CQ,4,2012-05-11,0,2
1,0,u0LXt3Uea_GidxRW1xcsfg,8UIishPUD92hXtScSga_gw,Always drove past this coffee house and wonder...,gkCorLgPyQLsptTHalL61g,4,2015-10-27,1,0
2,0,u0LXt3Uea_GidxRW1xcsfg,w41ZS9shepfO3uEyhXEWuQ,"Not bad!! Love that there is a gluten-free, ve...",5r6-G9C4YLbC7Ziz57l3rQ,3,2013-02-09,1,0
3,0,u0LXt3Uea_GidxRW1xcsfg,PIsUSmvaUWB00qv5KTF1xA,This is currently my parents new favourite res...,z8oIoCT1cXz7gZP5GeU5OA,4,2013-05-01,1,0
4,0,u0LXt3Uea_GidxRW1xcsfg,PdZ_uFjbbkjtm3SCY_KrZw,Server was a little rude.\r\n\r\nOrdered the c...,XWTPNfskXoUL-Lf32wSk0Q,3,2011-09-28,5,1

In [10]:
import get_attributes

In [11]:
get_attributes.get_user_features(user, review, business)

C:\Users\Hoang\Principles of Data Science\get_attributes.py:113: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data.drop(["yelping_since"], axis=1, inplace=True)
C:\Users\Hoang\Principles of Data Science\get_attributes.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data["temp"] = pd.Series(temp).values
C:\Users\Hoang\Principles of Data Science\get_attributes.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data.drop("elite", axis=1, inplace=True)
C:\Users\Hoang\Principles of Data Science\get_attributes.py:136: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data["past_reviews"] = temp_series.values

In [12]:
data = pd.read_csv("user_features.csv")

In [13]:
data

,user_id,review_count,average_stars,months_Yelping,useful,cool,funny,temp,past_reviews
0,BdoyadfDYtQY9txT62ApLw,4,4.17,16,0,0,0,2,"[('m2OL7kEeI8O7yfZuzLLPxg', ""['Latin American'..."
1,z6c8nSJNC-0bSqvdRdgHJA,13,3.87,70,3,1,1,2,"[('aLcFhMe6DDJ430zelCpd2A', ""['Tapas Bars', 'J..."
2,hh4WrGxpPYHm8lsgEfAgoQ,11,3.31,35,3,0,2,2,"[('44a_evCaWZ63cPA1kWPJOw', ""['Canadian (New)'..."
3,oZyiiNdA-I5zk_EHUmGRMQ,78,3.72,90,64,27,55,18,"[('CN5nuUQod0f8g3oh99qq0w', ""['Soup', 'Ramen',..."
4,evWhQrO8ApTyKYhs0bcxMQ,3,1.33,18,0,0,0,2,"[('2aIgbnGUg8VC0u9iXO-wnQ', ""['Tex-Mex', 'Rest..."
5,vzxXfgEqqMthrbtJJD4yDQ,3,2.75,83,0,0,0,2,"[('BxCzy1WOVxOrr_G7V4BIvg', ""['Diners', 'Cafes..."
6,Bnuhu0cts7h-ZtKpohCHXw,4,3.00,38,0,0,0,2,"[('lmpRLpu-JSLfykxXttPgIA', ""['Food', 'Restaur..."
7,dk9_rlCzwC1pDjsLkUZ57Q,3,3.53,77,5,0,2,2,"[('RtUvSWO_UZ8V3Wpj0n077w', ""['Tapas Bars', 'J..."
8,hpkqa0oYHqrBAcYIqNhM5Q,3,4.20,105,1,1,0,2,"[('-smb9VnuwDyTeImkS8W5GQ', ""['Dive Bars', 'Ni..."
9,I5Qbp-aWTlhjnT9EkTAbkA,8,3.36,14,1,0,0,2,"[('I_eCXujGAbl1JKrye_419w', ""['Restaurants', '..."
10,SG70Hi2DTVnMJMf6aNctpg,7,4.00,43,5,0,1,2,"[('HGZh_GGToep5AMb9TikrmQ', ""['Food', 'Coffee ..."
11,fVny6uPNfuFy2-IuNIzW8w,13,3.73,59,0,0,0,2,"[('w9TXFk3zKcVQJ92Ow992mg', ""['American (Tradi..."
12,lMylkyWjfe1nka0cjeJYUA,10,3.15,106,33,0,1,2,"[('1baM3j-bqzUJaqRM2z2PtA', ""['Nightlife', 'Sh..."
13,bUui4g9YvU_SoB00nChJqA,3,2.67,48,0,0,0,2,"[('oDdJD8mwqCtR1tOP4EvqgQ', ""['Burgers', 'Rest..."
14,iaQXOdQhGWLcyRr85IY2Fw,3,3.85,63,0,0,0,2,"[('7gnYWanhD6O7qOF-NfPNhA', ""['Italian', 'Pizz..."
15,dxHYSoALgMkt6ahhmCUxhg,6,3.96,31,0,1,0,2,"[('olllmpQVBHwOQmarQro2fw', ""['Gastropubs', 'N..."
16,7OURjtceW40mhpRX9P2dDg,84,3.88,58,16,1,0,6,"[('zhoNuaWrB125_LRRVPWMSQ', ""['Nightlife', 'As..."
17,2EMNb3AUAvJzSy4Dsg0Rfw,6,3.63,117,47,1,1,2,"[('BlrvqjGanZvjlNsnIyvAXQ', ""['Breakfast & Bru..."
18,gjhlFWowxI01FuecrkkgQA,4,3.09,28,44,1,1,2,"[('NUHNLaMg7aMesMdAiie73w', ""['Restaurants', '..."
19,UzmKj22YRig4FdKbcuuURA,10,3.79,29,0,0,0,2,"[('CN5nuUQod0f8g3oh99qq0w', ""['Restaurants', '..."
20,84e2tyNQmdVAeiHbXMUsFg,3,2.67,50,2,0,0,2,"[('phPZ8TqDJE51PRe-rnI3dQ', ""['Restaurants', '..."
21,QimVuv_IPh5eVuXBb_cEtQ,7,4.00,108,1,0,0,2,"[('YWd0I1BxSzFG61lSyC3IyQ', ""['Tex-Mex', 'Brea..."
22,jnC1CcEF9KjCs2gw82SfSQ,40,3.11,56,58,2,8,2,"[('KFlwmysUsRUOx4-_5PQ8xA', ""['Middle Eastern'..."
23,Nf_QqEr5eY9ukEFi50lZBg,9,3.46,68,0,1,6,2,"[('mU4mvQSf81nLuxW1IC_mAA', ""['Pakistani', 'In..."
24,y1rDf4fbpgJpA6NUpTNJgA,4,4.06,40,0,0,0,2,"[('fGurvC5BdOfd5MIuLUQYVA', ""['Restaurants', '..."
25,awlLz4kcnWQ227clWnQT6g,4,3.73,72,0,0,6,2,"[('nWD8OWd_DAXGubGpFenmiw', ""['Mexican', 'Rest..."
26,_XljFQ7OH9JaFZJSNUWGuA,10,4.05,67,0,0,0,2,"[('qpqWDf2oLEy2fhhq9sqfNA', ""['Restaurants', '..."
27,XVB7A0KXfeXMp2ZY2VUJqA,4,3.00,29,0,1,7,2,"[('uChTCA6MsLAciDRklpO-Fw', ""['Greek', 'Restau..."
28,j33J-dMUy3r0LnE14JkFzQ,4,3.33,59,0,0,0,2,"[('HTr7gRurfw_A6EgwGEwc4g', ""['Bars', 'America..."
29,gsDD6rsLb1QKWG2aLWv19Q,17,4.30,21,0,0,0,2,"[('iGEvDk6hsizigmXhDKs2Vg', ""['Restaurants', '..."
...,...,...,...,...,...,...,...,...,...
301,8cYHQp4IQwE3P5Z8mGweMQ,7,3.06,86,143,110,71,42,"[('X6ZZksefmR_piQj2Gbnduw', ""['Korean', 'Resta..."
302,S9HyH4muuMH6BMoodFyFcg,4,3.56,117,6,2,0,18,"[('IxDYVpjEeCxZ8HsZnthvdw', ""['Restaurants', '..."
303,LIWe_6iOEdVliuhDqDSFww,4,3.40,35,0,0,0,2,"[('ii_zDR8crbQVJehMMWoCkQ', ""['Donuts', 'Coffe..."
304,drikmXGQ6LdT8FghCpLQqA,7,3.33,97,13,3,9,2,"[('CN5nuUQod0f8g3oh99qq0w', ""['Buffets', 'Japa..."
305,6IkaUWhIUG98VXqbrlREpw,17,4.33,56,2,0,2,2,"[('CrfANiUEzY0ZkvhQmtDiSA', ""['Restaurants', '..."
306,ivLtDaUkyrFjl8wndL1vyQ,21,3.83,79,3,2,1,2,"[('zfQ855VX3SMA_54oVSN5Cw', ""['Restaurants', '..."
307,LzfiVNRBPkApQEqpgjMYag,4,4.33,7,0,0,0,2,"[('CB8HrynUWR4Odnj-XTY-Ew', ""['Barbeque', 'Kor..."
308,JW487hqPl7Z2R8C9_welYA,5,3.79,28,2,0,0,2,"[('HkHTdTvzbn-bmeQv_-2u0Q', ""['Wigs', 'Shoppin..."
309,uhub28VgAGEnhAHM9cACXA,7,3.54,75,0,0,0,2,"[('ttuEwktrkmh3TUlSFPZqAA', ""['Mexican', 'Rest..."
310,vIjSA6rHk0UoXKJycGyXtQ,3,3.97,77,0,0,0,2,"[('iAxsnFs3qq0Qx1EJ1S9SoQ', ""['Bars', 'Japanes..."
311,KzAw1G5EsLnjIE8qoWNr7g,9,3.06,90,3,0,0,2,"[('l9vx-OTdDPU-oHZ17aVxdg', ""['Restaurants', '..."
312,N3N4rZRiLQtZzWuTE5ho2w,3,2.00,36,4,1,0,2,"[('SW0NcZwZsbSpsk0ZPgJKmQ', ""['Restaurants', '..."
313,17iYh7v5zhZXINObBfZLoA,23,3.26,67,3,0,1,2,"[('ZTgclQiedMle5k9Fy-aOoQ', ""['Canadian (New)'..."
314,fjNNUJS0dtMr7W0hHMiNVw,81,3.82,88,81,8,28,24,"[('tPyttXySi2eiE4K035Cnhg', ""['Coffee & Tea', ..."
315,kWEGCL6xRlJXyp8rgR8NGg,3,3.00,57,0,0,1,2,"[('_5McjQXLCBxZgxhW8sfrjQ', ""['Nightlife', 'Ba..."
316,NMNE7-h3CzIuKIVqoVttxg,5,2.50,52,0,0,0,2,"[('_X2GpJvazUrhRUgFn6Y66A', ""['Bars', 'Pubs', ..."
317,TFnq_xDN-YwgjVMyAPnzsw,3,3.63,87,0,0,0,2,"[('9cBklDZJZJFGY8_yIpRRHw', ""['Steakhouses', '..."
318,5tRusHDx8WspiF_H39kNRg,4,4.33,59,3,0,0,2,"[('zfQ855VX3SMA_54oVSN5Cw', ""['Asian Fusion', ..."
319,sHHXoA-eYoZW0210vao_fQ,9,3.80,25,0,0,0,2,"[('1w0Tko5c-8HxsAdOUX81lg', ""['Juice Bars & Sm..."
320,iQrPKomQlLCWXiYhhYkRBA,4,4.11,25,0,0,0,2,"[('PAZC7ENEmDDgNMZngJSxxg', ""['Nightlife', 'Pu..."
321,5AjXezqTQXyfbvyFqcXPKQ,3,4.00,42,0,0,0,2,"[('tvYID0arhN-shKGUrC1Wsg', ""['Middle Eastern'..."
322,_awBchFZin6HpXEgMAJt3w,8,3.13,48,1,1,1,2,"[('e41TP5cXZqSrz50xCBJqZw', ""['Food', 'Dessert..."
323,969SG_ugeil7enqeRntmHA,10,3.19,85,16,0,1,2,"[('3D-FJxp8bsBzm3zJVqs92g', ""['Grocery', 'Food..."
324,m_-pIACutb6_5w1GpHbpNg,44,4.00,52,5,6,6,12,"[('iGEvDk6hsizigmXhDKs2Vg', ""['Restaurants', '..."
325,LavKyK0FnmAuXESyVInvKg,3,4.25,28,0,0,0,2,"[('GHPsuPkFFazLPfh41vgEMg', ""['Restaurants', '..."
326,dwUMt2JL6Yxaj8iGRTJzQg,30,3.73,92,3,0,1,2,"[('O1TvPrgkK2bUo5O5aSZ7lw', ""['Restaurants', '..."
327,KCD7sG3PCXHwdexnZPu4eQ,6,4.83,44,0,0,0,2,"[('nOmR49imE4GtmwWVLkHS9A', ""['Bakeries', 'Cof..."
328,JRApNVkdTrm3sLs1pmkPWA,7,4.17,105,10,1,4,2,"[('T8J4WHgTmO83uD1BHya6ZQ', ""['Lebanese', 'San..."
329,gvFsN-UedIk-_EOpMRihIQ,8,3.64,43,1,1,1,2,"[('zW600wCsIlC2w5SQBNAo_w', ""['Restaurants', '..."
330,4uSjk1cryPttErTp6zwa3Q,42,4.09,106,609,600,557,18,"[('U3Ah385YhvlraXsKcEeZ4g', ""['Japanese', 'Bar..."